# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 멍청씨의 멍청한 블로그
email: dmkim1986@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   처음으로 도전하는 개발자 블로그입니다. 경력이 늘면 늘수록 부족함을 느껴 한번 진행해볼까합니다. 많은 응원부탁드립니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bmikethedreamer.github.io" # the base hostname & protocol for your site
github_username:  bmikethedreamer

# Build settings
markdown: kramdown
